srt {
    worker_threads  2;
    worker_connections 600;

    log_file /var/log/sls/error.log;
    log_level info;

    # Listener principal : 10000/UDP
    server {
        listen 10000;
        latency 300;

        domain_player     play;
        domain_publisher  publish;
        backlog 100;
        idle_streams_timeout 30;

        app {
            app_player     live;
            app_publisher  live;
            record_hls off;
        }
    }

    # Listener secours : 443/UDP (pour pare-feux restrictifs)
    server {
        listen 443;
        latency 300;

        domain_player     play;
        domain_publisher  publish;
        backlog 100;
        idle_streams_timeout 30;

        app {
            app_player     live;
            app_publisher  live;
            record_hls off;
        }
    }
}
